doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: 13
        charset: utf8
        schema_filter: ~^(?!(hdb_))~ # exclude Hasura schema
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
