apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.name" . }}-php
  labels:
  {{- include "api.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
type: Opaque
stringData:
  JWT_SECRET_KEY: {{ .Values.apache.jwtSecretKey }}
  JWT_PUBLIC_KEY: {{ .Values.apache.jwtPublicKey }}
  MAILER_DSN: {{ .Values.apache.mailerDsn | quote }}
  HASURA_ADMIN_SECRET: {{ tpl .Values.apache.hasuraAdminSecret $ | quote }}
  APP_HASURA_SECRET: {{ .Values.apache.appHasuraSecret | quote }}
  APP_SECRET: {{ .Values.apache.appSecret | quote }}
{{- if .Values.postgresql.enabled }}
  DATABASE_URL: "postgresql://postgres:{{ .Values.postgresql.postgresqlPassword }}@{{ .Values.postgresql.fullnameOverride }}.{{ .Release.Namespace }}.svc.cluster.local/{{ .Values.postgresql.postgresqlDatabase }}"
{{- else }}
  DATABASE_URL: {{ .Values.postgresql.dbUrl | quote }}
{{- end }}