apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.name" . }}-php
  labels:
  {{- include "api.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
type: Opaque
stringData:
  HASURA_ADMIN_SECRET: {{ .Values.hasura.adminSecret | quote }}
  APP_HASURA_BASIC_AUTH: {{ .Values.hasura.extraEnvVarsSecret.APP_HASURA_BASIC_AUTH | quote }}
  APP_SECRET: {{ .Values.apache.appSecret | quote }}
{{- if .Values.postgresql.enabled }}
  DATABASE_URL: "postgresql://postgres:{{ .Values.postgresql.postgresqlPassword }}@{{ .Values.postgresql.fullnameOverride }}.{{ .Release.Namespace }}.svc.cluster.local/{{ .Values.postgresql.postgresqlDatabase }}"
{{- else }}
  DATABASE_URL: {{ .Values.postgresql.dbUrl | quote }}
{{- end }}