# Read more about GraphQLite available options at: https://graphqlite.thecodingmachine.io/docs/symfony-bundle
graphqlite:
  debug:
    INCLUDE_DEBUG_MESSAGE: true
    INCLUDE_TRACE: true
    RETHROW_UNSAFE_EXCEPTIONS: false