{{- if .Values.apache.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "api.name" . }}-apache
  labels:
  {{- include "api.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "api.name" . }}-apache
  minReplicas: {{ .Values.apache.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.apache.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.apache.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.apache.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.apache.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.apache.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
