{{- if .Values.apache.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "api.apache.serviceAccountName" . }}
  labels:
  {{- include "api.labels" . | nindent 4 }}
  {{- with .Values.apache.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
