apiVersion: v1
kind: Pod
metadata:
  name: {{ include "api.name" . }}-apache
  labels:
    {{- include "api.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['{{ include "api.name" . }}-apache:{{ .Values.apache.service.port }}']
  restartPolicy: Never
