apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "api.name" . }}-apply-hasura-metadata
  labels:
  {{- include "api.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "3"
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
      {{- include "api.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "api.apache.serviceAccountName" . }}
      restartPolicy: Never
      containers:
        - name: job
          image: "{{ .Values.apache.image.repository }}:{{ .Values.apache.image.tag }}"
          imagePullPolicy: {{ .Values.apache.image.pullPolicy }}
          args:
            - "php"
            - "bin/console"
            - "hasura:metadata:apply"
            - "--no-interaction"
          envFrom:
            - configMapRef:
                name: {{ include "api.name" . }}-php
            - secretRef:
                name: {{ include "api.name" . }}-php